<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Category;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            [
                'name' => 'DECIMAL COLLECTION',
                'short_code' => 'DC',
                'slug' => 'decimal-collection',
                'title' => '',
                'sub_title' => '',
                'bolder_text' => '',
                'banner_image' => 'uploads/2024/03/banner.png',
                'image_path' => NULL,
                'description' => 'Research, Curation, and the ‘Right Intent’ set the tone for this new collection from Millimetre. Extending functionality with a higher-level of aesthetics,Collezione Decimmal provides a comprehensive solution aimed at achieving a harmonious blend of style and sophistication to your furniture and livingspaces. As another first for the industry, matching edgebands to the exact decor, not just in colour alone but in texture as well, is a testament to ourattention to detail. Collezione Decimmal invites you to embrace a new standard of sophistication and a solution for your design endeavours.',
                'parent_id' => null,
            ],
            [
                'name' => 'Solid',
                'short_code' => '',
                'slug' => 'solid',
                'title' => 'Decimal Collection',
                'sub_title' => 'ELEGANT COLLECTION OF SOLID',
                'bolder_text' => 'TWELVE & MONOCHROMES • GREYS & SHADES • WHITES & CREAMS • BLACKS & TINTSSOPHISTICATED • NEUTRAL • CONTEMPORARYSOLIDS',
                'banner_image' => NULL,
                'image_path' => 'uploads/2024/03/banner_2.png',
                'description' => '12 plain solid colours are presented as a careful pick, bases on market understanding. The choice of a monochromatic palette brings a sense of sophistication, allowing anexciting interplay between these shades and tints with other solids, woods or design decors to enhance the desired aesthetic.',
                'parent_id' => '1',
            ],
            [
                'name' => 'Wood',
                'short_code' => '',
                'slug' => 'wood',
                'title' => 'Decimal Collection',
                'sub_title' => 'ELEGANT COLLECTION OF SOLID',
                'bolder_text' => 'TWELVE & MONOCHROMES • GREYS & SHADES • WHITES & CREAMS • BLACKS & TINTSSOPHISTICATED • NEUTRAL • CONTEMPORARYSOLIDS',
                'banner_image' => NULL,
                'image_path' => 'uploads/2024/03/banner_2.png',
                'description' => '12 plain solid colours are presented as a careful pick, bases on market understanding. The choice of a monochromatic palette brings a sense of sophistication, allowing anexciting interplay between these shades and tints with other solids, woods or design decors to enhance the desired aesthetic.',
                'parent_id' => '1',
            ],
            [
                'name' => 'Textile',
                'short_code' => '',
                'slug' => 'textile',
                'title' => 'Decimal Collection',
                'sub_title' => 'ELEGANT COLLECTION OF SOLID',
                'bolder_text' => 'TWELVE & MONOCHROMES • GREYS & SHADES • WHITES & CREAMS • BLACKS & TINTSSOPHISTICATED • NEUTRAL • CONTEMPORARYSOLIDS',
                'banner_image' => NULL,
                'image_path' => 'uploads/2024/03/banner_2.png',
                'description' => '12 plain solid colours are presented as a careful pick, bases on market understanding. The choice of a monochromatic palette brings a sense of sophistication, allowing anexciting interplay between these shades and tints with other solids, woods or design decors to enhance the desired aesthetic.',
                'parent_id' => '1',
            ],
            [
                'name' => 'BANDEDGE',
                'short_code' => 'BE',
                'slug' => 'bandedge',
                'title' => 'BETTER FINISHED',
                'sub_title' => '',
                'bolder_text' => '',
                'banner_image' => 'uploads/2024/03/banner_1.png',
                'image_path' => NULL,
                'description' => 'Better aesthetics through seamless ‘no-aberration’ visual, T.O.Y.E is the cornerstone idea of COLLEZIONE DECIMMAL. Same asthe decor, with the same texture as on the decor. Because better visual is a higher level of sophistication',
                'parent_id' => null,
            ],
            [
                'name' => 'MASTER SUEDE',
                'short_code' => 'MS',
                'slug' => 'master-suede',
                'title' => '',
                'sub_title' => '',
                'bolder_text' => '',
                'banner_image' => NULL,
                'image_path' => NULL,
                'description' => '',
                'parent_id' => '2',
            ],
            [
                'name' => 'MORE LEATHER',
                'short_code' => 'ML',
                'slug' => 'ml',
                'title' => '',
                'sub_title' => '',
                'bolder_text' => '',
                'banner_image' => NULL,
                'image_path' => NULL,
                'description' => '',
                'parent_id' => '2',
            ],
            [
                'name' => 'MS',
                'short_code' => 'MS',
                'slug' => 'ms-wood',
                'title' => '',
                'sub_title' => '',
                'bolder_text' => '',
                'banner_image' => NULL,
                'image_path' => NULL,
                'description' => '',
                'parent_id' => '3',
            ],
            [
                'name' => 'MAX WOOD',
                'short_code' => 'MW',
                'slug' => 'mw',
                'title' => '',
                'sub_title' => '',
                'bolder_text' => '',
                'banner_image' => NULL,
                'image_path' => NULL,
                'description' => '',
                'parent_id' => '3',
            ],
            [
                'name' => 'MS',
                'short_code' => 'MS',
                'slug' => 'ms-textile',
                'title' => '',
                'sub_title' => '',
                'bolder_text' => '',
                'banner_image' => NULL,
                'image_path' => NULL,
                'description' => '',
                'parent_id' => '4',
            ],
            [
                'name' => 'MASTER ENTWINE',
                'short_code' => 'ME',
                'slug' => 'me',
                'title' => '',
                'sub_title' => '',
                'bolder_text' => '',
                'banner_image' => NULL,
                'image_path' => NULL,
                'description' => '',
                'parent_id' => '4',
            ],
            [
                'name' => 'MASTER SUEDE',
                'short_code' => 'MS',
                'slug' => 'ms-bandedge',
                'title' => '',
                'sub_title' => '',
                'bolder_text' => '',
                'banner_image' => NULL,
                'image_path' => NULL,
                'description' => '',
                'parent_id' => '5',
            ],
            [
                'name' => 'MAX WOOD',
                'short_code' => 'MW',
                'slug' => 'mw-bandedge',
                'title' => '',
                'sub_title' => '',
                'bolder_text' => '',
                'banner_image' => NULL,
                'image_path' => NULL,
                'description' => '',
                'parent_id' => '5',
            ],
            [
                'name' => 'MORE LEATHER',
                'short_code' => 'ML',
                'slug' => 'ml-bandedge',
                'title' => '',
                'sub_title' => '',
                'bolder_text' => '',
                'banner_image' => NULL,
                'image_path' => NULL,
                'description' => '',
                'parent_id' => '5',
            ],
            [
                'name' => 'MASTER ENTWINE',
                'short_code' => 'ME',
                'slug' => 'me-bandedge',
                'title' => '',
                'sub_title' => '',
                'bolder_text' => '',
                'banner_image' => NULL,
                'image_path' => NULL,
                'description' => '',
                'parent_id' => '5',
            ],
        ];

        foreach ($categories as $categoryData) {
            Category::create($categoryData);
        }
    }
}
